#!/usr/bin/env ruby
require 'facter'

dry_run = false
stop_services = /nova|cinder|glance|keystone|neutron|sahara|murano|ceilometer|heat|swift|apache2|httpd/

# files #

if Facter.osfamily=~ /debian/i
   puts  "Enabling WSGI module"
   system "a2enmod wsgi || exit 0"
end

# services #

services = `service --status-all 2>&1`

services_to_stop = services.inject([]) do |services_to_stop, service|
  fields = service.chomp.split
  running = if fields[4] == "running..."
    fields[0]
  elsif fields[1] == "+"
    fields[3]
  else
    nil
  end

  if running =~ stop_services
    # replace wrong service name
    running = 'httpd' if running == 'httpd.event'
    running = 'openstack-keystone' if running == 'keystone' and Facter.osfamily=="RedHat"
    services_to_stop << running
  else
    services_to_stop
  end
end

puts "Stop these services: #{services_to_stop.join ', '}"

services_to_stop.each do |service|
  system "#{dry_run ? 'echo' : ''} service #{service} stop 2>&1"
end

# pids #

ps=`ps axo pid,cmd`

pids_to_kill = ps.inject([]) do |pids_to_kill, process|
  fields = process.chomp.split
  pid = fields.shift
  cmd = fields.join ' '
  if cmd =~ stop_services
    pids_to_kill << pid
  else
    pids_to_kill
  end
end

puts "Kill these pids: #{pids_to_kill.join ', '}"

system "#{dry_run ? 'echo' : ''} kill -9 #{pids_to_kill.join ' '}" if pids_to_kill.any?
