# This is example config file for Astute. Your config file should be placed
# to /opt/astute/astute.conf. You can check default values in config.rb file.
---
# mc_retries is used in mclient.rb file.
# MClient tries mc_retries times to call MCagent before failure.
mc_retries: 5
# puppet_timeout is used in puppetd.rb file.
# Maximum time (in seconds) Astute waits for the whole deployment.
puppet_timeout: 3600
# puppet_deploy_interval is used in puppetd.rb file.
# Astute sleeps for puppet_deploy_interval seconds, then check Puppet agents
# statuses again.
puppet_deploy_interval: 2
# puppet_fade_timeout is used in puppetd.rb file.
# After Puppet agent has finished real work it spend some time to graceful exit.
# puppet_fade_timeout means how long (in seconds) Astute can take for Puppet
# to exit after real work has finished.
puppet_fade_timeout: 120
# puppet_fade_interval is used in puppetd.rb file.
# Retry every puppet_fade_interval seconds to check puppet state if it was
# in 'running' state.
puppet_fade_interval: 10
